Controllers/AdminestratorController.cs
using ITIProject.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting.Internal;
using System.Linq.Expressions;

namespace ITIProject.Controllers
{
    public class AdminestratorController : Controller
    {
        ECommerceAContextApp _context = new ECommerceAContextApp();

        private readonly IWebHostEnvironment _webHostEnvironment ;
        public AdminestratorController(IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
        }

        [HttpGet]
        public IActionResult LogIn()
        {

            return View();
        }
        [HttpPost]
        public IActionResult LogIn(Adminestrator admin)
        {

            if (ModelState.IsValid)
            {
                return RedirectToAction("AllItems");
            }
            return View(admin);
        }

        [HttpGet]
        public IActionResult AllItems()
        {

            //ViewBag.categories = _context.Categories.Select(c => c.Name).ToList();
            return View(_context.Products.ToList());
        }
        [HttpGet]

        public IActionResult NewItem()
        {
            ViewBag.categories = _context.Categories.ToList();
            return View();
        }

        [HttpPost]
        public IActionResult NewItem(Product product, [FromRoute] int Id)
        {
            IFormFile imageFile = Request.Form.Files["imageFile"];
            string image = string.Empty;

            if (ModelState.IsValid)
            {
                if (imageFile != null && imageFile.Length > 0)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(imageFile.FileName);

                    string filePath = Path.Combine(_webHostEnvironment.WebRootPath, "Images", fileName);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        imageFile.CopyTo(stream);
                    }
                    product.ImagePath = "/Images/" + fileName;
                    image = "/Images/" + fileName;
                }
                //product.ImagePath = image;
                _context.Products.Add(product);
                _context.SaveChanges();
                return RedirectToAction("AllItems");
            }
            ViewBag.categories = _context.Categories.ToList();
            return View(product);
        }


        [HttpGet]
        public IActionResult NewCategory()
        {
            return View();
        }

        [HttpPost]
        public IActionResult NewCategory(Category category)
        {
            if(ModelState.IsValid)
            {
                _context.Categories.Add(category);
                _context.SaveChanges();
                return RedirectToAction("AllItems");
            }
            return View(category);
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            ViewBag.categories = _context.Categories.ToList();
            var product =  _context.Products.Find(id);
            return View(product);
        }

        [HttpPost]
        //IFormFile imageFile = Request.Form.Files["imageFile"];
        public IActionResult Update(Product product, [FromRoute] int Id/*, [FromRoute] string ImagePath*/)
        {
            IFormFile imageFile = Request.Form.Files["imageFile"];
            if (ModelState.IsValid)
            {
                if (imageFile != null && imageFile.Length > 0)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(imageFile.FileName);
                    string filePath = Path.Combine(_webHostEnvironment.WebRootPath, "Images", fileName);
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        imageFile.CopyTo(stream);
                    }
                    product.ImagePath = "/Images/" + fileName;
                }
                else
                    product.ImagePath = product.ImagePath;
                _context.Products.Update(product);
                _context.SaveChanges();
                return RedirectToAction("AllItems");
            }
            ViewBag.categories = _context.Categories.ToList();
            return View(product);
        }

        [HttpGet]
        public ActionResult DeleteItem(int id)
        {
            var product = _context.Products.Find(id);
            ViewBag.category = _context.Categories.Find(product.CategoryId).Name;
            return View(product);
        }

        [HttpPost]
        public IActionResult DeleteItem(Product product)
        {
            
            
                _context.Products.Remove(product);
                _context.SaveChanges();
                return RedirectToAction("AllItems");
        }

    }
}

Controllers/CustomerController.cs
using ITIProject.Models;
using ITIProject.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace ITIProject.Controllers
{
    public class CustomerController : Controller
    {
        ECommerceAContextApp _context = new ECommerceAContextApp();

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Register(Customer customer)
        {
            if(ModelState.IsValid)
            {
                var cart = new Cart();
                _context.Carts.Add(cart);
                _context.SaveChanges();
                customer.CartId = cart.Id;
                _context.Customers.Add(customer);
                _context.SaveChanges();
                return RedirectToAction("LogIn");
            }
            return View(customer);
        }

        public IActionResult AgeValidation(int Age)
        {
            if (Age >= 18)
                return Json(true);
            return Json(false);
        }

        [HttpGet]
        public IActionResult LogIn()
        {
            
            return View();
        }
        [HttpPost]
        public IActionResult LogIn(Customer customer, [FromRoute] int CartId)
        {
           
            if (ModelState.IsValid)
            {
                return RedirectToAction("Browse", new { CartId = CartId });
            }
            return View(customer);
        }

        public IActionResult Browse()
        {
            ViewBag.categories = _context.Categories.ToList();   
            return View(_context.Products.ToList());
        }

       public IActionResult ViewCart()
        {
            ViewBag.categories = _context.Categories.ToList();
            return View(_context.ProductOrders.Where(po => po.CartId == 5).ToList());
        }


        public IActionResult RemoveFromCart(ProductOrder po, [FromRoute] int id)
        {
            _context.ProductOrders.Remove(po);
            _context.SaveChanges();
            return RedirectToAction("ViewCart");
        }


        public IActionResult MakeOrder(int Id)
        {
            FinalInvoiceViewModel invoice = new FinalInvoiceViewModel();
            var targetItems = _context.ProductOrders.Where(po => po.CartId == Id);
            decimal TotalCost = targetItems.Sum(po => po.Cost);
            var totalQuantity = targetItems.Sum(po => po.Quantity);
            var products = _context.Products.ToList();

            var order = new Order();
            foreach(var item in targetItems)
            {
                var Name = products.FirstOrDefault(p => p.Id == item.ProductId).Name;
                var Cost = item.Cost;
                var Quantity = item.Quantity;
                var finalItem = new ItemViewModel();
                finalItem.ItemCost = Cost;
                finalItem.ItemQuantity = Quantity;
                finalItem.ItemName = Name;
                invoice.Items.Add(finalItem);
            }
        
            order.TotalQuantity = totalQuantity;
            order.TotalCost = TotalCost;
            order.CartId = Id;
            invoice.TotalCost = TotalCost;
            invoice.CartId = Id;
            invoice.TotalQuantity = totalQuantity;
            _context.Orders.Add(order);
            _context.ProductOrders.RemoveRange(targetItems);
            _context.SaveChanges();
            invoice.OrderId = order.Id;
            return View(invoice);
        }

        public IActionResult AddToCart(Product product, [FromRoute] int Id)
        {
            var productPrice = _context.Products.Find(Id).Price; ;
            if (_context.ProductOrders.Any(po => po.ProductId== Id))
            {
                AddRepeatedItem(Id, productPrice);
            }
            else
            {
                ProductOrder productOrder = new ProductOrder();
                productOrder.Quantity += 1;
                productOrder.ProductId = Id;
                productOrder.Cost = productPrice;
                productOrder.CartId = 5;
                _context.ProductOrders.Update(productOrder);

            }

            _context.Products.Find(product.Id).Quantity -= 1;          
            _context.SaveChanges();
            return RedirectToAction("Browse");
        }

        public void AddRepeatedItem(int id, decimal cost)
        {
            var item = _context.ProductOrders.FirstOrDefault(po => po.ProductId == id);
            item.Quantity += 1;
            item.Cost += cost;
        }
    }

    
}

Views/Shared/_HomeLayout.cshtml
@{
    ViewData["Title"] = "_HomeLayout";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP.NETCoreMVCDay01</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASP.NETCoreMVCDay01.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="css/StyleSheet.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Customer" asp-action="LogIn">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" @* asp-area="" asp-controller="Customer" asp-action="ViewCart" *@>View Cart</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" @* asp-area="" asp-controller="Customer" asp-action="Browse" *@>Browse</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Adminestrator" asp-action="LogIn">Adminestration</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted" style="text-align: center;">
        <div class="container">
            <div class="copyright">
                Copyright &copy; 2023 <a href="#">E-Commerce</a>. All rights reserved.
            </div>
            <div class="links">
                <a href="#" style="margin-right: 10px;">Privacy Policy</a>
                <a href="#" style="margin-right: 10px;">Sitemap</a>
                <a href="#" style="margin-right: 10px;">Contact Us</a>
            </div>
            <div class="social">
                <a href="#"><i class="fab fa-facebook-f"></i></a>
                <a href="#"><i class="fab fa-twitter"></i></a>
                <a href="#"><i class="fab fa-linkedin-in"></i></a>
                <a href="#"><i class="fab fa-youtube"></i></a>
            </div>
            <div class="email-signup" style="margin-top: 10px;">
                <input type="email" placeholder="Enter your email address" style="padding: 5px;">
                <button style="padding: 5px 10px; background-color: #333; color: #fff; border: none;">Sign up for our newsletter</button>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP.NETCoreMVCDay01</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASP.NETCoreMVCDay01.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASP.NETCoreMVCDay01</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ASP.NETCoreMVCDay01 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_SharedLayout.cshtml
@{
    ViewData["Title"] = "_SharedLayout";
}



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP.NETCoreMVCDay01</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASP.NETCoreMVCDay01.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="css/StyleSheet.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Customer" asp-action="LogIn">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="ViewCart">View Cart</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Browse">Browse</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Adminestrator" asp-action="LogIn">Adminestration</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted" style="text-align: center;">
        <div class="container">
            <div class="copyright">
                Copyright &copy; 2023 <a href="#" style=" text-decoration:none;">E-Commerce</a>. All rights reserved.
            </div>
            <div class="links">
                <a href="#" style="margin-right: 10px; text-decoration:none;">Privacy Policy</a>
                <a href="#" style="margin-right: 10px;text-decoration:none;">Sitemap</a>
                <a href="#" style="margin-right: 10px;text-decoration:none;">Contact Us</a>
            </div>
            <div class="social">
                <a href="#"><i class="fab fa-facebook-f"></i></a>
                <a href="#"><i class="fab fa-twitter"></i></a>
                <a href="#"><i class="fab fa-linkedin-in"></i></a>
                <a href="#"><i class="fab fa-youtube"></i></a>
            </div>
            <div class="email-signup" style="margin-top: 10px;">
                <input type="email" placeholder="Enter your email address" style="padding: 5px;">
                <button style="padding: 5px 10px; background-color: #333; color: #fff; border: none;">Sign up for our newsletter</button>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>